services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend
    restart: unless-stopped
    expose:
      - "5000"
    env_file:
      - ./backend/.env
    environment:
      - NODE_ENV=production
    networks:
      - app-network
    depends_on:
      - mongo

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend
    restart: unless-stopped
    ports:
      - "5173:80"      # nginx serves on 80, not 5173
    networks:
      - app-network
    depends_on:
      - backend

  mongo:
    image: mongo:7
    container_name: mongo
    restart: unless-stopped
    volumes:
      - mongo_data:/data/db
    networks:
      - app-network

  nginx:
    image: nginx:alpine
    container_name: nginx
    restart: unless-stopped
    ports:
      - "8080:8080"
    volumes:
      - ./API-Gateway/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./API-Gateway/nginx/includes:/etc/nginx/includes
      - ./API-Gateway/nginx/routes:/etc/nginx/routes
    depends_on:
      - backend
    networks:
      - app-network

include:
  - docker-compose.redis.yml

networks:
  app-network:
    driver: bridge

volumes:
  mongo_data: