location = /_auth_validate {
  internal;

  proxy_pass http://auth_backend/validate;
  proxy_pass_request_body off;

  proxy_set_header Content-Length "";
  proxy_set_header Authorization $http_authorization;
  auth_request_set $user_id $upstream_http_x_user_id;
}

error_page 401 = @auth_error;

location @auth_error {
  return 401 '{"error":"Unauthorized"}';
}
