location = /health {
    access_log off;

    proxy_pass https://backend-ccf7.onrender.com/health;
    proxy_set_header Host backend-ccf7.onrender.com;
    include /etc/nginx/includes/proxy.conf;
    proxy_ssl_server_name on;
}
