server {
    listen 8080;

    include /etc/nginx/includes/health.conf;
    include /etc/nginx/includes/metrics.conf;

    # App1 routes
    location /api/products/ {
        #  client protection FIRST
        limit_req zone=per_ip burst=5 nodelay;
        limit_req_status 429;

        limit_conn conn_limit 10;

       # auth_request /_auth_validate; 

        proxy_cache app_cache;
        proxy_cache_valid 200 30s;
        proxy_cache_methods GET;
        proxy_cache_key "$scheme$request_method$host$request_uri";

        add_header X-Cache-Status $upstream_cache_status;

        proxy_pass http://backend:5000;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header Authorization $http_authorization;
    }

    # Auth service routes'
    location /api/users/ {
        proxy_pass         http://backend:5000;
        proxy_set_header   Host $host;
        proxy_set_header   X-Real-IP $remote_addr;
    }

   
    include /etc/nginx/includes/rate-limit.conf;

    include /etc/nginx/includes/auth-jwt.conf;
}

