worker_processes auto;

events {
  worker_connections 1024;
}

http {
  include       mime.types;
  default_type  application/json;

  sendfile on;
  keepalive_timeout 65;

  include /etc/nginx/includes/rate-limit-zones.conf;  

  #Caching 
  include /etc/nginx/includes/caching.conf;


  # Logging 
  include /etc/nginx/includes/logging.conf;

  # Upstreams (logical backend groups)
  upstream app1_backend {
    server api-gateway-p6u1.onrender.com:443;
  }

  include /etc/nginx/routes/*.conf;
}
