worker_processes auto;

events {
  worker_connections 1024;
}

http {
  resolver 8.8.8.8;
  
  include       mime.types;
  default_type  application/json;

  sendfile on;
  keepalive_timeout 65;

  include /etc/nginx/includes/rate-limit-zones.conf;  

  #Caching 
  include /etc/nginx/includes/caching.conf;


  # Logging 
  access_log off;  

 
  include /etc/nginx/routes/*.conf;
}
